"""users.oidc_sub for OIDC/SSO login

Links a local account to its IdP identity (Authentik). NULL = password-only
user. Unique — one local account per IdP subject.

Revision ID: 003
Revises: 002
Create Date: 2026-07-10 12:24:13.272967

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: str | Sequence[str] | None = '002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oidc_sub', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_users_oidc_sub', 'users', ['oidc_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_oidc_sub', 'users', type_='unique')
    op.drop_column('users', 'oidc_sub')
    # ### end Alembic commands ###
