"""categories.condition_tiers for market-price grounding

The condition tiers a kind of item sells in (games: sealed/graded/cib/loose;
firearms: new/used/surplus/antique). Written once by the agent's grounding pass
and then reused, so the same tier keeps the same name across runs — a drifting
vocabulary splits one tier's observations over several spellings and shrinks the
sample counts confidence is derived from. NULL = not generated yet.

Revision ID: 004
Revises: 003
Create Date: 2026-08-08 14:40:51.812026

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "004"
down_revision: str | Sequence[str] | None = "003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("condition_tiers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "condition_tiers")
    # ### end Alembic commands ###
